### ISSUE TITLE
Unable to install Moq 

### ISSUE THREAD

**Issue by robobat** [moq/moq#17]
Hi, 

Pretty new to Xamarin and Android.  This is the error I'm getting using Xamarin Studio version 5.9.7 (build 22) and xamarin android Version 5.1.7

Could not install package 'Moq 4.2.1510.2205'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any idea what the issue could be?  Is there something else I need to include?

Thanks

**Comment by Dalanie** [comment]
Same issue here...

**Comment by jonasflesch** [comment]
Same here.

**Comment by kzu** [comment]
Not supported.
