### ISSUE TITLE
Mocked method returns mock even for null if property predicate is specified.

### ISSUE THREAD

**Issue by jroitgrund** [moq/moq#19]
This test fails:

    var artist = new Artist();
    artist.Id = "4576";
    var deserializer = Mock.Of<IXmlDeserializer<Album>>(
        d => d.Deserialize("foo").Artist == artist);
    Assert.IsNull(deserializer.Deserialize(null));

Even stranger is that if I replace the IsNull assert with

    Assert.AreEqual("4576", deserializer.Deserialize(null).Artist.Id)

it passes.

If instead I do

    var album = new Album();
    album.Artist = artist;
    var deserializer = Mock.Of<IXmlDeserializer<Album>>(
        d => d.Deserialize("foo") == album);

everything works as expected. This behavior is unintuitive. If specifying predicates on properties of the returned object results in strange behavior it should throw an error instead.

**Comment by kzu** [comment]
Plz report at https://github.com/moq/moq4/issues
