### ISSUE TITLE
.Net Core 1.0.0 Support

### ISSUE THREAD

**Issue by RehanSaeed** [moq/moq#20]
I'm using xUnit with Moq 4.6.25-alpha and get the following error:

> The type initializer for 'Moq.Mock`1' threw an exception.
> The type initializer for 'Moq.Proxy.CastleProxyFactory' threw an exception.
> Could not load file or assembly 'System.Diagnostics.TraceSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

This is my project.json file. I understand the the Castle.Core dependency may be where I really need to raise an issue.

```
{
  "version": "1.0.0-*",

  "testRunner": "xunit",

  "dependencies": {
    "Moq": "4.6.25-alpha",
    "xunit": "2.2.0-beta2-build3300",
    "dotnet-test-xunit": "2.2.0-preview2-build1029"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": [
        "dotnet5.4"
      ]
    },
    "net461": {
    }
  }
}
```

**Comment by kzu** [comment]
Yep, we don't use that API AFAIK
