### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by PivotalAnimal** [moq/moq#21]
Is this project no longer? It seems outdated. Are there any plans to upgrade to project.json?

**Comment by kzu** [comment]
Duplicate of https://github.com/moq/moq4/pull/225

**Comment by kzu** [comment]
BTW, project.json doesn't seem like it will have a long life, so we may never "upgrade" to it. 

See https://github.com/Microsoft/msbuild/issues?q=is%3Aissue+is%3Aopen+label%3AParity-XProj
